__version__: str

def SkToPk(SK: bytes) -> bytes: ...
def Sign(SK: bytes, message: bytes) -> bytes: ...
def Verify(PK: bytes, message: bytes, signature: bytes) -> bool: ...
def Aggregate(signatures: list[bytes]) -> bytes: ...
def _AggregatePKs(PKs: list[bytes]) -> bytes: ...
def FastAggregateVerify(PKs: list[bytes], message: bytes, signature: bytes) -> bool: ...
def AggregateVerify(PKs: list[bytes], messages: list[bytes], signature: bytes) -> bool: ...
def VerifyMultipleAggregateSignatures(SignatureSets: list[list[bytes]]) -> bool: ...
